# Disable power-saving dowshift for the left trackball (scrolling)
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=0
CONFIG_PMW3610_REST1_DOWNSHIFT_TIME_MS=0
CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS=0
CONFIG_PMW3610_REST3_DOWNSHIFT_TIME_MS=0